### ISSUE TITLE
Improve readme with info on data storage

### ISSUE THREAD

**Issue by iHiD** [exercism/development-environment#14]
@saschamann suggested adding into the readme about the following:

> Docker for Windows (not sure about other OS) has a setting for where it should store the virtual harddrives (? not sure about the details tbh). It defaults to C: which may not be what you want.

**Comment by joshgoebel** [comment]
This should also include fixing "down" vs "stop" perhaps explaining the difference.  Right now it seems the most important persistent data store is SQL.
