### ISSUE TITLE
Change "down" to "stop"

### ISSUE THREAD

**Issue by iHiD** [exercism/development-environment#18]
This should also include fixing "down" vs "stop" perhaps explaining the difference.  Right now it seems the most important persistent data store is SQL.

_Originally posted by @joshgoebel in https://github.com/exercism/development-environment/issues/14#issuecomment-673784574_

**Comment by ErikSchierboom** [comment]
I've checked the README, but it refers to using `down`. Is this issue about using `stop` instead of `down` (as in, the reverse of the title)?

**Comment by iHiD** [comment]
Yes. Sorry. Title updated :)
