### ISSUE TITLE
Wait for website to finish

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/development-environment#21]
At the moment, running `./bin/start` outputs:

> It may take just a moment for everything to spool up.
>
>    http://localhost:3020/

It would be nice if we could detect when the website is actually running.

**Comment by joshgoebel** [comment]
Ha, nice.  I wasn't worried about being so fancy. :)

**Comment by SleeplessByte** [comment]
There are various tools for this, such as `wait-on`, but they all boil down to pinging some tcp address.

**Comment by joshgoebel** [comment]
You could probably use curl/wget or something but now we're back to requiring things in the users local env...
