### ISSUE TITLE
Sort windows line endings

### ISSUE THREAD

**Issue by iHiD** [exercism/development-environment#37]
@SleeplessByte tells me that this repo is not setup with correct line endings so this doesn't run on windows wsl by default. Line endings need adding to `.gitattributes` to fix this. [This explains more](https://docs.github.com/en/free-pro-team@latest/github/using-git/configuring-git-to-handle-line-endings#example).

This is the option we want:
```
text eol=lf
```
Git will always convert line endings to LF on checkout. You should use this for files that must keep LF endings, even on Windows. Since this must run in a linux context, probably a good choice.

---

@ErikSchierboom As the master of the Windows universe, I'll assign this one to you. Fire questions in @SleeplessByte's direction, not mine, please, as I have no idea 🙂 

 Should we also do the same for `v3-website`?

**Comment by ErikSchierboom** [comment]
I've created [a PR](#38). The `v3-website` already has a `.gitattributes` file.
