### ISSUE TITLE
Two Problems using stack.default.yml

### ISSUE THREAD

**Issue by verdammelt** [exercism/development-environment#47]
(This issue report is based on behavior seen in commit 31fb904e58b84b4661113a16045eeb1595191913.)

I copied `stack.default.yml` to `stack.yml` as directed by the README and encountered two problems. Both where easy to work around but I wanted to report them in case they could be easily fixed or to at least let people know what to do if they hit the problems and could not easily debug the problem themselves.

## #1:  undefined method `data' for nil:NilClass (NoMethodError)

Running `./bin/start` resulted in the stack trace:

```ruby
Traceback (most recent call last):
	11: from ./bin/build_stack:4:in `<main>'
	10: from /Users/mark/SRC/exercism/development-environment/lib/docker_compose.rb:17:in `build_stack'
	 9: from /Users/mark/SRC/exercism/development-environment/lib/docker_compose/stack.rb:13:in `write_docker_compose'
	 8: from /Users/mark/SRC/exercism/development-environment/lib/docker_compose/stack.rb:46:in `prepare'
	 7: from /Users/mark/SRC/exercism/development-environment/lib/docker_compose/stack.rb:23:in `enabled_services'
	 6: from /Users/mark/SRC/exercism/development-environment/lib/docker_compose/stack.rb:23:in `map'
	 5: from /Users/mark/SRC/exercism/development-environment/lib/docker_compose/stack.rb:23:in `block in enabled_services'
	 4: from /Users/mark/SRC/exercism/development-environment/lib/docker_compose/stack.rb:30:in `resolve_group'
	 3: from /Users/mark/SRC/exercism/development-environment/lib/docker_compose/stack.rb:30:in `map'
	 2: from /Users/mark/SRC/exercism/development-environment/lib/docker_compose/stack.rb:32:in `resolve_group'
	 1: from /Users/mark/SRC/exercism/development-environment/lib/docker_compose/stack.rb:37:in `resolve_dependencies'
/Users/mark/SRC/exercism/development-environment/lib/docker_compose/stack.rb:58:in `service_for': undefined method `data' for nil:NilClass (NoMethodError)
```

Some debugging showed that this was happening because `analyzers` was included in `enabled` key but contained `none` in its section of `groups`. Commented out `analyzers` resulted in the same problem for other items with `none` values in `groups (`representers`, `language-servers`).

Workound: commented out these items or replace the `none` keys with appropriate values.

## #2: `Pulling language-server-proxy  ... error`

After working around the above error, running `./bin/start --pull` results in an error:

```
ERROR: for language-server-proxy  pull access denied for exercism/language-server-proxy, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: pull access denied for exercism/language-server-proxy, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Workaround: comment out `language-server-proxy` from the `groups`/`tooling` section.

**Comment by verdammelt** [comment]
Of course my "workaround" may not be working as I am getting a crash on the website when trying to access it (`localhost:3020`):

```
ActionView::Template::Error (Webpacker can't find application.js in /usr/src/app/public/packs/manifest.json. Possible causes:
website_1                  | server   | 1. You want to set webpacker.yml value of compile to true for your environment
website_1                  | server   |    unless you are using the `webpack -w` or the webpack-dev-server.
website_1                  | server   | 2. webpack has not yet re-run to reflect updates.
website_1                  | server   | 3. You have misconfigured Webpacker's config/webpacker.yml file.
website_1                  | server   | 4. Your webpack configuration is not creating a manifest.
website_1                  | server   | Your manifest contains:
website_1                  | server   | {
website_1                  | server   | }
website_1                  | server   | ):
website_1                  | server   |      6:     = csrf_meta_tags
website_1                  | server   |      7:     = csp_meta_tag
website_1                  | server   |      8:     = action_cable_meta_tag
website_1                  | server   |      9:     = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
website_1                  | server   |     10:     = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
website_1                  | server   |     11:
website_1                  | server   |     12:     %meta{ name: "language-server-url", content: Exercism.config.language_server_url }
website_1                  | server   |
website_1                  | server   | app/views/layouts/application.html.haml:9
```

**Comment by ErikSchierboom** [comment]
@verdammelt I've fixed the second issue. I had pushed an invalid image name to Docker for the language server proxy 🤦

**Comment by ErikSchierboom** [comment]
@verdammelt The first issue is being fixed in this PR: https://github.com/exercism/development-environment/pull/48

**Comment by ErikSchierboom** [comment]
I'm looking into the third issue.

**Comment by ErikSchierboom** [comment]
@verdammelt It could be partly due to the website Docker image having a build error. This will be fixed in https://github.com/exercism/v3-website/pull/306

**Comment by ErikSchierboom** [comment]
@verdammelt Another PR to help fix this: https://github.com/exercism/development-environment/pull/49

**Comment by ErikSchierboom** [comment]
@verdammelt The issues should now all be fixed if the latest versions are pulled.

**Comment by iHiD** [comment]
Thanks so much for the info @verdammelt :)

**Comment by verdammelt** [comment]
OK, the two stack.yml based problems have been resolved. Still getting the webpack error but that I guess would be a website problem not a development-environment problem.

I'll double check that I'm running the latest of the website and if needed report a problem on https://github.com/exercism/website

I'll close this issue for now.

Thanks.

**Comment by iHiD** [comment]
>  Still getting the webpack error but that I guess would be a website problem not a development-environment problem.

You might need to leave it for a few (5?) mins. It takes a while for the JS to compile the first time.

If that's still not working after 5mins, let me know and I'll look more.

**Comment by verdammelt** [comment]
I will *attempt* to be patient. I have just completed a purge of all my docker images to make sure I get all the crisp new ones when I pull.

**Comment by iHiD** [comment]
The excitement **is** hard to contain 😉

**Comment by verdammelt** [comment]
Image started at: `2020-11-27T14:14:54.545369511Z` 

Compilation completed at: `2020-11-27T14:22:51.587429389Z`

I've lived through ~1+ hour compiles with C++ I guess I shouldn't complain (too much) about 8 minutes...
