### ISSUE TITLE
Use apt-get instead of apt get

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/development-environment#5]
Use `apt-get` instead of `apt get`

**Comment by iHiD** [comment]
@joshgoebel Did you do this everywhere?

**Comment by joshgoebel** [comment]
Where are you even seeing "apt get"?  I use apt-get everywhere.

It only weird use is in website

> apt install -y ./google-chrome-stable_current_amd64.deb && \

And I don't know the "correct" syntax there (maybe dpkg?) so I just left it alone since it works.

Can you clarify?

**Comment by iHiD** [comment]
I believe this was @SleeplessByte's point originally. DJ?

**Comment by SleeplessByte** [comment]
If we don't need user interface, we probably never want to use `apt`. It works, but is not backwards compatible with _future previous versions_.

**Comment by iHiD** [comment]
OK, thanks both.

I've assigned this to Erik to work out for the chrome install one. If anyone PRs a solution before he's back, great, otherwise he can work it out :)

**Comment by SleeplessByte** [comment]
@ErikSchierboom I think

```
DEBIAN_FRONTEND=noninteractive apt-get install -y ./google-chrome-stable_current_amd64.deb
```

**Comment by SleeplessByte** [comment]
@thexa4 wrote a blog post about this, so you can bookmark something if this is something your forget (I do).

https://blog.delftsolutions.nl/software/2020/08/20/using-apt-during-continuous-integration/
