### ISSUE TITLE
Add daemon setting.

### ISSUE THREAD

**Issue by iHiD** [exercism/development-environment#9]
Can we add a config setting for daemon, which is set to true by default, but if false just doesn't use the -d flag? I would choose to run this not in daemon mode so that the logs stream in the console.

@joshgoebel @ErikSchierboom Whichever of you gets round to this first, please add a comment to say you're working on it :)

**Comment by joshgoebel** [comment]
Or just have a --tail flag?

**Comment by ErikSchierboom** [comment]
I'll work on this
